services:
  __DB_SERVICE__

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9101"
    environment:
      MINIO_ROOT_USER: minecms
      MINIO_ROOT_PASSWORD: minecmsminecms
    ports:
      - "9100:9000"
      - "9101:9101"
    volumes:
      - minecms-files:/data

volumes:
  minecms-db:
  minecms-files:
